name: exercise7a
description: Face detection + Firebase upload demo

publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.0
  provider: ^6.0.0

  firebase_core: 2.9.0
  firebase_storage: 11.0.3
  google_mlkit_face_detection: 0.5.0

  flutter_local_notifications: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
