// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwrdIU_XpvpNjlcBMqzGYVbfL6ZPvAYrI',
    appId: '1:761115423237:web:09a43df8cdfb160ef4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    authDomain: 'xintong-spring2025.firebaseapp.com',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
    measurementId: 'G-D5P84VRC5M',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYuuAsR88u1VP-WBRrd7dNSXfqi9cUFnQ',
    appId: '1:761115423237:ios:017162da0fdf6ec9f4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
    androidClientId: '761115423237-7564jks91g06c64ksqv10h39keqaci3b.apps.googleusercontent.com',
    iosClientId: '761115423237-s05fhs395cub89r2bqtqa6ae5jfoi92u.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise7a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwrdIU_XpvpNjlcBMqzGYVbfL6ZPvAYrI',
    appId: '1:761115423237:web:80a4651547acd9aef4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    authDomain: 'xintong-spring2025.firebaseapp.com',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
    measurementId: 'G-NBMVMZG3N6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYuuAsR88u1VP-WBRrd7dNSXfqi9cUFnQ',
    appId: '1:761115423237:ios:017162da0fdf6ec9f4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
    androidClientId: '761115423237-7564jks91g06c64ksqv10h39keqaci3b.apps.googleusercontent.com',
    iosClientId: '761115423237-s05fhs395cub89r2bqtqa6ae5jfoi92u.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise7a',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlnDqVy3GKjJSMMxqRrLz3fM_gXvlfCA',
    appId: '1:761115423237:android:b34368abdec83117f4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
  );

}