// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwrdIU_XpvpNjlcBMqzGYVbfL6ZPvAYrI',
    appId: '1:761115423237:web:09a43df8cdfb160ef4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    authDomain: 'xintong-spring2025.firebaseapp.com',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
    measurementId: 'G-D5P84VRC5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlnDqVy3GKjJSMMxqRrLz3fM_gXvlfCA',
    appId: '1:761115423237:android:0b981025cc76224ff4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYuuAsR88u1VP-WBRrd7dNSXfqi9cUFnQ',
    appId: '1:761115423237:ios:0d24613649a957a4f4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
    androidClientId: '761115423237-7564jks91g06c64ksqv10h39keqaci3b.apps.googleusercontent.com',
    iosClientId: '761115423237-ou6i6ng0u8a4ku67ut51q3i84l3tqhf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYuuAsR88u1VP-WBRrd7dNSXfqi9cUFnQ',
    appId: '1:761115423237:ios:0d24613649a957a4f4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
    androidClientId: '761115423237-7564jks91g06c64ksqv10h39keqaci3b.apps.googleusercontent.com',
    iosClientId: '761115423237-ou6i6ng0u8a4ku67ut51q3i84l3tqhf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwrdIU_XpvpNjlcBMqzGYVbfL6ZPvAYrI',
    appId: '1:761115423237:web:4bf34c45e8290762f4626c',
    messagingSenderId: '761115423237',
    projectId: 'xintong-spring2025',
    authDomain: 'xintong-spring2025.firebaseapp.com',
    storageBucket: 'xintong-spring2025.firebasestorage.app',
    measurementId: 'G-C4Q1TMKP1F',
  );
}
